In [21]:
import numpy as np
#question 1
x=[1,2,3,4,5,6]
N=7
p=list(range(N))
l=[]
for s in range(len(x)):
    for i in p:
        r=x[(s+1)*-1]**p[((i+1)*-1)]
        l.append(r)
b=np.asarray(l)
c=b.reshape(len(x),N)[::-1]
print("input={}\t N={}\n\n\tYour vandermonde matrix is \n {}\n {}".format(x,N,"="*50,c))

input=[1, 2, 3, 4, 5, 6]	 N=7

	Your vandermonde matrix is 
 [[    1     1     1     1     1     1     1]
 [   64    32    16     8     4     2     1]
 [  729   243    81    27     9     3     1]
 [ 4096  1024   256    64    16     4     1]
 [15625  3125   625   125    25     5     1]
 [46656  7776  1296   216    36     6     1]]


In [22]:
#question 2
x=[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
k=3
n=len(x)
moving_average=n-k+1
moving_average
result=[]
s=list(range(moving_average))
for i in s:
    print("The {}th moving average of {},{},{} = {}".format(i+1,x[i],x[i+1],x[i+2],x[i]+x[i+1]+x[i+2]/4))

The 1th moving average of 3,5,7 = 9.75
The 2th moving average of 5,7,2 = 12.5
The 3th moving average of 7,2,8 = 11.0
The 4th moving average of 2,8,10 = 12.5
The 5th moving average of 8,10,11 = 20.75
The 6th moving average of 10,11,65 = 37.25
The 7th moving average of 11,65,72 = 94.0
The 8th moving average of 65,72,81 = 157.25
The 9th moving average of 72,81,99 = 177.75
The 10th moving average of 81,99,100 = 205.0
The 11th moving average of 99,100,150 = 236.5
